POST http://localhost:3001/api/notes
Content-Type: application/json
# Authorization: Bearer 

{
  "content": "Single page apps use token based authentication",
  "important": true,
  "userId": "684e6105761d17ad901e9f37"
}